# Generated by Django 5.2 on 2025-04-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_birthday_alter_customuser_phone'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='group',
            field=models.ManyToManyField(related_name='customuser', to='auth.group'),
        ),
    ]
