# Generated by Django 5.2 on 2025-04-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_customuser_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sub_role',
        ),
    ]
