# Generated by Django 5.2 on 2025-04-23 17:53

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcamp',
            name='days',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bootcamp',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bootcampregistration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='0912', max_length=128, region='IR', unique=True),
        ),
    ]
