# Generated by Django 5.2 on 2025-04-23 17:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0002_alter_bootcamp_days_alter_bootcamp_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootcampregistration',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True),
        ),
    ]
