# Generated by Django 5.2 on 2025-04-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0004_smslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smslog',
            name='bootcamp_name',
        ),
    ]
