# Generated by Django 5.2 on 2025-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0005_remove_smslog_bootcamp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('unsuccess', 'Unsuccess')], max_length=100),
        ),
    ]
