# Generated by Django 5.2 on 2025-04-28 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0006_alter_smslog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootcampregistration',
            old_name='student',
            new_name='volunteer',
        ),
    ]
