# Generated by Django 5.2 on 2025-04-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0007_rename_student_bootcampregistration_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcampregistration',
            name='installment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
